import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"


[window]
opacity = 0.95

padding.x = 10
padding.y = 10

decorations = "Full"
decorations_theme_variant = "Dark" # "Dark"

[font]
size = 7.0

[font.bold]
# family = "MesloLGS Nerd Font Mono"
family = "CaskaydiaCove Nerd Font"
# family = "JetbrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
# family = "MesloLGS Nerd Font Mono"
family = "CaskaydiaCove Nerd Font"
# family = "JetbrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
# family = "MesloLGS Nerd Font Mono"
family = "CaskaydiaCove Nerd Font"
# family = "JetbrainsMono Nerd Font"
style = "Italic"

[font.normal]
# family = "MesloLGS Nerd Font Mono"
# family = "JetbrainsMono Nerd Font"
family = "CaskaydiaCove Nerd Font"
style = "Regular"
